[project]
name = "cells"
version = "0.1.0"
description = "Project to deal with cells recognition"
channels = ["conda-forge", "default", "bioconda"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = ">=3.10,<3.11"
pixi-pycharm = ">=0.0.5,<0.1"
tensorflow = ">=2.13.0,<2.14.0"
numpy = "==1.26.4"
cellpose = ">=3.0.9"
pims = ">=0.7,<1"
typer = ">=0.12.3,<0.13"
loguru = ">=0.7.2,<0.8"
[pypi-dependencies]
jupyter = "*"
pycomfort = "*"
cellpose = { version = "*", extras = ["gui"] }
pyqt5 = "*"
